### ISSUE TITLE
主题推荐

### ISSUE THREAD

**Issue by xibo-sun** [Nalleyer/67JamRule#2]
最近看到一个主题，想学习一下。

主题名字：打造次时代的 UI 界面
参考资料（目标）：https://www.youtube.com/watch?v=vqZjZ6yv1lA （28：35开始）。感觉及其炫酷屌炸天。

还有个小建议，能否建立一个文件夹，可以提供相关资料整理（比如：主题建议、参考资料、学习心得等）

**Comment by Nalleyer** [comment]
收到，明天建立。也欢迎直接提pr

**Comment by Nalleyer** [comment]
已在 8b624e52a531f7e3be3ce89004bdadf7d2359a5b 中处理。感谢提议。
